server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:recipe
    driverClassName: org.h2.Driver
    username: testuser
    password: testpwd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

entityManager:
  packagesToScan: com.abnamro.recipe

logging:
  level:
    org:
      hibernate:
        type: trace